### ISSUE TITLE
How does this work?

### ISSUE THREAD

**Issue by Starbors** [CleverProgrammers/nodejs-zoom-clone#10]
Hi how does this work?

and what apps do l need ....

**Comment by ProgrammerPro94** [comment]
It works with the help of node.js and webrtc's peer.

**Comment by Starbors** [comment]
No l mean how can l run dis

**Comment by codergautam** [comment]
Vscode powershell terminal 
node server.js

**Comment by Starbors** [comment]
> Vscode powershell terminal
> node server.js

Error: Cannot find module 'C:\Users\Ryan samaeian\Desktop\Lettters\nodejs-zoom-clone-master\server.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1029:15)
    at Function.Module._load (internal/modules/cjs/loader.js:898:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []

**Comment by codergautam** [comment]
Make sure to install all the required modules...

npm install express


npm install socket.io


npm install peerjs

**Comment by Starbors** [comment]
ty

**Comment by Starbors** [comment]
But when l run it it does not reply with anything,howerver it did open node.js and asked me to to an internet thing

**Comment by Starbors** [comment]
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3030
    at Server.setupListenHandle [as _listen2] (net.js:1313:16)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1447:7)
    at Object.<anonymous> (C:\Users\Ryan samaeian\Desktop\Lettters\nodejs-zoom-clone-master (1)\nodejs-zoom-clone-master\server.js:42:8)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)    
    at internal/main/run_main_module.js:17:47
Emitted 'error' event at:
    at WebSocketServer.<anonymous> (C:\Users\Ryan samaeian\Desktop\Lettters\nodejs-zoom-clone-master (1)\nodejs-zoom-clone-master\node_modules\peer\dist\src\instance.js:53:13)       
    at WebSocketServer.emit (events.js:315:20)
    at WebSocketServer._onSocketError (C:\Users\Ryan samaeian\Desktop\Lettters\nodejs-zoom-clone-master (1)\nodejs-zoom-clone-master\node_modules\peer\dist\src\services\webSocketServer\index.js:49:14)
    at WebSocketServer.<anonymous> (C:\Users\Ryan samaeian\Desktop\Lettters\nodejs-zoom-clone-master (1)\nodejs-zoom-clone-master\node_modules\peer\dist\src\services\webSocketServer\index.js:22:55)
    at WebSocketServer.emit (events.js:315:20)
    at Server.emit (events.js:315:20)
    at emitErrorNT (net.js:1340:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 3030
}
Woah

**Comment by Starbors** [comment]
OHH ok so l did it but when l run node server.js it doesnt reply or do anything

**Comment by codergautam** [comment]
Idk man... Worked for me

**Comment by Starbors** [comment]
Can you show me a demo of the app?

**Comment by idsus** [comment]
Me too

**Comment by codergautam** [comment]
https://google-meet-clone.herokuapp.com/ Sorry for late reply

**Comment by idsus** [comment]
Really, that was the application they made?

**Comment by codergautam** [comment]
Yes, I made some modifications like the home screen... there is code https://github.com/codergautam/GoogleMeetClone

**Comment by Starbors** [comment]
hmm??

**Comment by Starbors** [comment]
ye its fixed no need to advertise your project

**Comment by Starbors** [comment]
> Really, that was the application they made?

no man THATS not at all

**Comment by Boopalan-M** [comment]
> https://google-meet-clone.herokuapp.com/ Sorry for late reply

in this how can i add screenshare functionality

**Comment by LaiqueMirza** [comment]
@Starbors @idontcareofusername  guyz i know what you are doing wrong. first you have to go in that directory than install, than run .

 Just run the following code step by step.

step 1

cd nodejs-zoom-clone-master

step 2

npm install

step 3

npm start

than go to localhost:3030 and it would be running

**Comment by idsus** [comment]
ok the port is 3030 ill try this
