### ISSUE TITLE
APP CRASH PLEASE HELP!!

### ISSUE THREAD

**Issue by Starbors** [CleverProgrammers/nodejs-zoom-clone#14]
```
PS C:\Users\Ryan samaeian\Desktop\Lettters\nodejs-zoom-clone-master\nodejs-zoom-clone-master> nodemon server.js
[nodemon] 2.0.4
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node server.js`
events.js:292
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::3030
    at Server.setupListenHandle [as _listen2] (net.js:1313:16)
    at listenInCluster (net.js:1361:12)
    at Server.listen (net.js:1447:7)
    at Object.<anonymous> (C:\Users\Ryan samaeian\Desktop\Lettters\nodejs-zoom-clone-master\nodejs-zoom-clone-master\server.js:42:8)
    at Module._compile (internal/modules/cjs/loader.js:1200:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1220:10)
    at Module.load (internal/modules/cjs/loader.js:1049:32)
    at Function.Module._load (internal/modules/cjs/loader.js:937:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)    
    at internal/main/run_main_module.js:17:47
Emitted 'error' event at:
    at WebSocketServer.<anonymous> (C:\Users\Ryan samaeian\Desktop\Lettters\nodejs-zoom-clone-master\nodejs-zoom-clone-master\node_modules\peer\dist\src\instance.js:53:13)
    at WebSocketServer.emit (events.js:315:20)
    at WebSocketServer._onSocketError (C:\Users\Ryan samaeian\Desktop\Lettters\nodejs-zoom-clone-master\nodejs-zoom-clone-master\node_modules\peer\dist\src\services\webSocketServer\index.js:49:14)
    at WebSocketServer.<anonymous> (C:\Users\Ryan samaeian\Desktop\Lettters\nodejs-zoom-clone-master\nodejs-zoom-clone-master\node_modules\peer\dist\src\services\webSocketServer\index.js:22:55)
    at WebSocketServer.emit (events.js:315:20)
    at Server.emit (events.js:315:20)
    at emitErrorNT (net.js:1340:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 3030
}
[nodemon] app crashed - waiting for file changes before starting...

```
So l get this can someone please help me!!!

**Comment by rachitakeshri** [comment]
Have you tried using another port ?

**Comment by ret394** [comment]
```
https://github.com/CleverProgrammers/nodejs-zoom-clone/blob/master/server.js#L42
```

Use port above 8000. 
If you get error, use port 9000. It's quite a popular choice for news items in USA. 
Though I prefer port 10k as in 10 000. It's way more general.

**Comment by Starbors** [comment]
> ```
> https://github.com/CleverProgrammers/nodejs-zoom-clone/blob/master/server.js#L42
> ```

could you explain more?

**Comment by Starbors** [comment]
Ye it willl crash with all of them lol!

**Comment by idsus** [comment]
Still the issue?

**Comment by ret394** [comment]
https://github.com/ret394/nodejs-zoom-clone/blob/e3dd9ee9a242036c5daeb0f459c1d06d99d190bc/server.js#L42-L45

thanks

**Comment by Starbors** [comment]
ye still appcrash

**Comment by ret394** [comment]
I'm not following the issue, but are you using nodemon to run it? 
Using `nodemon server.js`

thanks

**Comment by Starbors** [comment]
Yes

**Comment by idsus** [comment]
Thanks for the command!

**Comment by Starbors** [comment]
@ret394 You didnt even add a port!

nodemon needs it

**Comment by ret394** [comment]
>@ret394 You didnt even add a port!

It's nothing. "Pay no attention to it."

Use it on Ubuntu, though.

thanks a lot. ^_^

**Comment by anujmittal2308** [comment]
https://stackoverflow.com/questions/72003682/cant-fix-expresspeerserver-is-not-a-function-in-server-js
